name: Staging Push

on:
  push:
    branches:
      - 'staging'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: runbooksolutions/agent:dev
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            output: RBSAgent.exe
          - os: ubuntu-latest
            output: RBSAgent
          - os: macos-latest
            output: RBSAgent.app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Publish Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'  # Adjust the Python version as needed
          spec: 'app.py'  # Adjust the path to your .spec or .py file
          requirements: 'requirements.txt'  # Adjust the path to your requirements.txt file
          upload_exe_with_name: ${{matrix.output}}  # Adjust the desired artifact name
          options: --onefile, --name "RBSAgent", --windowed